name: ğŸš€ publish

on:
  workflow_run:
    workflows: ['ğŸ’‚ CodeQL']
    branches: [prod]
    types:
      - completed
    check_run:
      types: [completed]
      conclusion: [success]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“– checkout
        uses: actions/checkout@v2
      - name: ğŸ“¦ï¸ node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: ğŸš€ publish package to npm
        run: yarn install && yarn publish_package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
