name: ğŸš€ publish

on:
  workflow_run:
    workflows: ['ğŸ’‚ CodeQL']
    branches: [prod]
    types:
      - completed
    check_run:
      types: [completed]
      conclusion: [success]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“– checkout
        uses: actions/checkout@v2
      - name: â“ï¸ verify project changes
        uses: tj-actions/verify-changed-files@v5.5
        with:
          files: |
            package
      - name: Display changed files
        if: steps.changed_files.outputs.files_changed == 'false'
        run: exit 1
      - name: ğŸ“¦ï¸ node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: ğŸš copy files
        run: cp README.md package/README.md && cp LICENCE package/LICENCE
      - name: ğŸš€ publish package to npm
        working-directory: package/
        run: yarn install && yarn publish_package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
